server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/**
            - Path=/swagger-ui/**
            - Path=/swagger-ui.html

        - id: user-service-crud
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: elogio-service-crud
          uri: lb://elogio-service
          predicates:
            - Path=/elogios/**

        - id: reclamacao-service-crud
          uri: lb://reclamacao-service
          predicates:
            - Path=/reclamacoes/**

        - id: sugestao-service-crud
          uri: lb://sugestao-service
          predicates:
            - Path=/sugestoes/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
